version: "3.4"  # optional since v1.27.0

services:
  app:
    container_name: app
    build: ./UI
    volumes: 
      - './UI/src/app'
    ports:
      -  "4200:4200"
    depends_on: 
      - api
    command: 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  api:
    container_name: api
    build: ./Backend
    ports:
      - "5000:5000"
    restart: always
    depends_on: 
      - db
  db:
    container_name: database
    build: ./Backend/data/
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: admin
      POSTGRES_DB: triage
    ports:
        - 5432:5432
    restart: always
  ml:
    container_name: ml
    build: ./ML
    ports:
      - "6006:6006"
    depends_on: 
      - db


